spring:
  data:
    mongodb:
      host: ${systemEnvironment[OPENSHIFT_MONGODB_DB_HOST]}
      port: ${systemEnvironment[OPENSHIFT_MONGODB_DB_PORT]}
      database: shop
      username: ${systemEnvironment[OPENSHIFT_MONGODB_DB_USERNAME]}
      password: ${systemEnvironment[OPENSHIFT_MONGODB_DB_USERNAME]}
mvc:
  view:
    suffix: .jsp
    prefix: /views/
error:
  whitelabel:
    enabled: true