spring:
  application:
     name: shop
  data:
    mongodb:
      host: ${systemEnvironment[MONGODB_DB_HOST]}
      port: ${systemEnvironment[MONGODB_DB_PORT]}
      database: shop
      username: ${systemEnvironment[MONGODB_DB_USERNAME]}
      password: ${systemEnvironment[MONGODB_DB_PASSWORD]}
mvc:
  view:
    suffix: .jsp
    prefix: /views/
error:
  whitelabel:
    enabled: true