spring:
  application:
     name: shop
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shop     
  mvc:
    view:
      suffix: .jsp
      prefix: /views/
server:
  error:
    whitelabel:
      enabled: true  