spring:
  application:
     name: shop
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shop
      username: admin
      password: admin
mvc:
  view:
    suffix: .jsp
    prefix: /views/
error:
  whitelabel:
    enabled: true